Feature/user login api
RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary pull request #11
Opened 2022-01-26 21:17 UTC by yaman3bd

2022-01-27 18:06 UTC, felmez approved these changes
good work

2022-01-27 18:09 UTC, felmez approved these changes

2022-01-27 18:09 UTC, felmez commented on src/routers/user.js
> +  'login',
maybe '/login'

2022-01-27 18:09 UTC, felmez commented on src/routers/user.js
> +  'register',
here also '/register' since its coming from /users but there it will be /usersregister

2022-01-27 19:17 UTC, halitbatur requested changes
Overall good job, some a few changes that needs to be addressed.

2022-01-27 19:17 UTC, halitbatur commented on src/controllers/user.js
> +
extra new line

2022-01-27 19:17 UTC, halitbatur commented on src/controllers/user.js
> +    }
new line needed after if

2022-01-27 19:17 UTC, halitbatur commented on src/controllers/user.js
> +};
new line needed after this

2022-01-27 19:17 UTC, halitbatur commented on src/controllers/user.js
> +const logout = async (req, res) => {
this function is declared async but I cannot see any `await` being used inside of it.

2022-01-27 19:17 UTC, halitbatur commented on src/controllers/user.js
> +};
new line needed

2022-01-27 19:17 UTC, halitbatur commented on src/routers/user.js
> +const { check } = require('express-validator');
require statements should be at the beginning please move these after requiring express.

2022-01-27 19:17 UTC, halitbatur commented on src/routers/user.js
> +);
new line after this

2022-02-01 09:34 UTC, halitbatur approved these changes
@yaman3bd good work!

2022-02-01 14:53 UTC, halitbatur commented
@yaman3bd update branch and solve conflicts then its ready to be merged.

2022-02-02 09:24 UTC, merged