Feature/is admin middleware
RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary pull request #17
Opened 2022-01-29 10:01 UTC by felmez

2022-01-29 18:00 UTC, yaman3bd requested changes

2022-01-29 18:07 UTC, yaman3bd requested changes

2022-01-29 18:07 UTC, yaman3bd commented on src/middlewares/isLogged.js
> +  const { token } = req.cookies;
here the token name too
![image](https://user-images.githubusercontent.com/58285821/151672107-72ad57fe-94b9-4186-88b6-e9537873e827.png)

2022-01-29 18:07 UTC, yaman3bd commented on src/middlewares/isLogged.js
> +  const { token } = req.cookies;
here the token name too
![image](https://user-images.githubusercontent.com/58285821/151672107-72ad57fe-94b9-4186-88b6-e9537873e827.png)

2022-01-29 18:07 UTC, yaman3bd commented on src/middlewares/isLogged.js
> +    .status(400)
status code 401 because the user is not unauthorized to see the content or do some actions

2022-01-29 18:07 UTC, yaman3bd commented on src/middlewares/isLogged.js
> +        .status(400)
status code should be 401 for Unauthorized actions

2022-01-29 18:07 UTC, yaman3bd commented on src/middlewares/isLogged.js
> +  SECRET_KEY,
why are you exporting SECRET_KEY?

2022-01-30 12:01 UTC, felmez commented on src/middlewares/isAdmin.js
> +  const { token } = req.cookies;
i think i answered these questions before but somehow it does not show, anyway for now i think token is more readable and we should go with that

2022-01-30 12:03 UTC, felmez commented on src/middlewares/isAdmin.js
> +  const { token } = req.cookies;
i think i answered these question but somehow they not showing, anyway for now i think token is more readable so we can go with that

2022-01-31 12:35 UTC, yaman3bd commented on src/middlewares/isAdmin.js
> +  const { token } = req.cookies;
yes I agree I will change it in my code

2022-02-01 00:07 UTC, Amr-Nash commented on src/middlewares/isAdmin.js
> +const jwt = require('jsonwebtoken');
I think you branched this branch "feature/isAdminMiddleware" from "feature/isLoggedMiddleware" not from "main" maybe you would have to empty the file "isLogged.js" in this branch to merge with no problems

2022-02-01 00:35 UTC, Amr-Nash commented on src/middlewares/isAdmin.js
> +const jwt = require('jsonwebtoken');
or you can merge "feature/isLoggedMiddleware" into "feature/isAdminMiddleware" then delete "feature/isLoggedMiddleware" 
lastly merge "feature/isAdminMiddleware" to "main"

2022-02-01 09:36 UTC, halitbatur approved these changes
Looks good, please make sure next time that you branch out of main and not have pervious branches working on the same branch

2022-02-01 10:10 UTC, felmez commented
i emptied the isLogged file so now it show not have conflict

2022-02-01 10:21 UTC, Amr-Nash approved these changes
thanks and well done

2022-02-01 10:21 UTC, merged

2022-02-01 10:28 UTC, felmez commented
conflict solved but we dont have isLogged now why this is happened ??

2022-02-01 10:32 UTC, halitbatur commented
@felmez isLogged shouldn't be emptied.. you should have merged with main and resolved conflicts emptying isLogged and PRing that cleared the file

2022-02-01 10:42 UTC, felmez commented
yeah i noticed something strange because when i edited the file isLogged in this branch it was the latest file from isLogged in main i guess this happened because we have already merged the isLogged with main before editing. makes sense now thanks a lot