Install Swagger Package #42
RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary pull request #45
Opened 2022-02-01 20:54 UTC by Amr-Nash

Add swagger to 'package.json'

2022-02-01 21:05 UTC, felmez requested changes

2022-02-01 21:05 UTC, felmez commented on package.json
> +    "swagger": "^0.7.5",
i think we are not going to this package specifically but instead we are going to use this one swagger-ui-express https://www.npmjs.com/package/swagger-ui-express so we can serve all the api from json file

2022-02-02 10:43 UTC, felmez approved these changes
good work

2022-02-02 13:39 UTC, halitbatur approved these changes
lgtm

2022-02-02 13:40 UTC, merged