project endpoint v2
RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary pull request #49
Opened 2022-02-02 15:43 UTC by edaguler00

2022-02-02 19:54 UTC, felmez requested changes
need some improvements

2022-02-02 20:30 UTC, felmez requested changes

2022-02-02 20:30 UTC, felmez commented on src/controllers/project.js
> +            "project": isDone,
here the project should only update the isDone field but here what is isDone ??

2022-02-02 20:30 UTC, felmez commented on src/controllers/project.js
> +        });
we should return something as response after deleting and also try catch deleting maybe something happened while trying to delete or maybe the project does not exist

2022-02-02 20:30 UTC, felmez commented on src/routers/project.js
> +const projectController = require("../controllers/project");
here in the other part of the file we used project instead of projectController so here also we should go with the same naming

2022-02-02 20:30 UTC, felmez commented on src/routers/project.js
> +router.put("/id", projectController.updateProject);
params are written like this => /:id

2022-02-02 20:30 UTC, felmez commented on src/routers/project.js
> +router.put("/id/finish", projectController.doneProject);
same here /:id

2022-02-02 20:30 UTC, felmez commented on src/routers/project.js
> +router.delete("/id", projectController.removeProject);
same here => /:id

2022-02-07 11:52 UTC, felmez commented
@halitbatur and this also what is happening with this pr ?

2022-02-10 09:59 UTC, halitbatur commented
@edaguler00 status on this? it's been more than a week since the last review.

2022-02-16 17:14 UTC, felmez requested changes
good work overall

2022-02-16 17:14 UTC, felmez commented on src/controllers/project.js
> +            "userID": mongoose.Types.ObjectId(donation.userID),
these quotes wrapping on userID can be removed lets use the same format everywhere

2022-02-16 18:54 UTC, felmez approved these changes

2022-02-17 13:45 UTC, halitbatur reviewed
change the controller naming as @felmez requested, update this with the main branch and its ready to be merged

2022-02-17 13:45 UTC, halitbatur commented on src/controllers/project.js
> +
this line shouldn't be empty

2022-02-17 18:18 UTC, yaman3bd requested changes

2022-02-18 10:43 UTC, halitbatur commented
@yaman3bd PTAL

2022-02-18 11:08 UTC, yaman3bd requested changes

2022-02-18 11:08 UTC, yaman3bd commented on src/controllers/project.js
> +      category: [],
it should be 'categories' not category please check the project model to get the correct props

2022-02-18 11:08 UTC, yaman3bd commented on src/controllers/project.js
> +    newProjects.category.push(...project.categories);
this one too should be categories the prop name I mean

2022-02-18 11:20 UTC, yaman3bd requested changes

2022-02-18 11:20 UTC, yaman3bd commented on src/controllers/project.js
> +    project.categories.push(newCategory);
and here just do
   project.categories.push(...categories);

2022-02-18 11:20 UTC, yaman3bd commented on src/controllers/project.js
> +  const { title, description, /* category //BUG not used */ donation } =
here category not used
but categories do

you just should name the parameter categories

2022-02-18 11:20 UTC, yaman3bd commented on src/controllers/project.js
> +    const newCategory = {
and from  line 47 to 49 should be deleted

2022-02-18 11:33 UTC, felmez commented
@edaguler00 make sure to do `git pull origin feature/crud_project_endpointv2` on this branch before committing new changes since we solved the conflicts and merged the updated main FYI

2022-02-22 13:53 UTC, halitbatur approved these changes

2022-02-22 13:53 UTC, merged