Feat: add tests, closes #44
RCDD-202110-TUR-BEW/backend-capstone-turkey-bursapediary pull request #71
Opened 2022-02-12 10:51 UTC by felmez

- [ ] - **nodemailer testing** #44
- [ ] - testing functionality of sending an email after the user successfully registered in from the /register endpoint
- [ ] - make sure that the email is not send when the register response is successful
- [ ] - **middleware testing** #43 
- [ ] - testing the isLogged middleware functionality that check the existence of the encrypted token that is generated and saved in cookies after the user logged in
- [ ] - make sure that the token is valid and contains the required credentials for the user
- [ ] - make sure to not let the user perform action if the token is not valid or expired
- [ ] - test the functionality of the isAdmin middleware where its checking the already logged in user to perform admin level tasks
- [ ] - isAuthorUser testing
- [ ] - **project support controller testing**
- [ ] - **user profile testing**
- [ ] - **project profile testing**
- [ ] - **reviews testing**
- [ ] - **comments testing**
- [ ] - **oauth google/github routes testing** 

closes #44

2022-02-13 20:33 UTC, yaman3bd approved these changes
great job 👍

2022-02-14 08:55 UTC, halitbatur requested changes

2022-02-14 08:55 UTC, halitbatur commented on .env.example
>  DB_URI=mongodb://127.0.0.1:27017/DB_NAME
there's no variable for the TEST_DB_URI, please make sure that both the DB_URI and the TEST_DB_URI are hosted on Mongodb atlas

2022-02-15 13:12 UTC, halitbatur commented
@felmez CI is failing here do you need help with it?

2022-02-17 06:58 UTC, halitbatur approved these changes

2022-02-17 06:58 UTC, merged